# -*- coding: utf-8 -*-
"""T1&T2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QUB8ABa1zSgvEopWKdewhV64Nknmk4dB
"""

a = 1
b = 2.01
c = 'string'
print(type(a),type(b), type(c))

x=8
y=4
a=9
z = complex(x,y)
v = complex(a)
print(v)
print(z)
x = y

print(v)
print(z)

x = input()
print(x)

x = int(input())
y = int(input())
z = x + y
res = z + 30
print(res)

z = input("enter something : ")
try:
  if type(eval(z)) == float:
    print(z, 'is a floating number')
  elif type(eval(z)) == bool:
    print(z, 'is a boolean')
  elif type(eval(z)) == int:
    print(z, 'is a integer')
except:
  print('it is a string')
  
  
print(type(z))

li = []
h= int(input())
j= int(input())
l= int(input())
if l == 1:
  print('addition =', h+j)
elif l == 2:
  print('substraction =', h-j)
elif l == 3:
  print('division =', h/j)
elif l == 4:
  print('multiplication =', h*j)
elif l == 5:
  first = int(input())
  second = int(input())
  li = [h,j,first,second]
  whole = sum(li)
  average = whole/len(whole)
  print(average)
else:
  print('nothing')

d = int(input('enter a number: '))
li = []
for i in li:
  if d < 0:
    break
    print('its over')
  else:
    continue
    print('good going')

for u in range(2000,3200):
  if u%5 and u%7 == 0:
  return 
    print(u)

#6
123
##
0
1
2
4
5
##
0
1
2
3
4
count = 0
while True:
  print(count)
  count += 1
  if count >= 5:
    break

for i in range(0,6):
  i += i
  if i == 3:
    break
  else:
    continue
print(i)

