# -*- coding: utf-8 -*-
"""T6,T7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ESaNTh4uRoyWjgjvDvd8jfhMxV_Dc364
"""

a-5

a = 3
a + ""

import sys
name = sys.argv[1]
open(name)
print(name)

def finding_uppercase(entry):
  return [x for x in entry if x == x.upper()]
finding_uppercase("Lingu")

list1 = ['Smit', 'Jaya', 'Rayyan']
list2 = ['CSE', 'Networking', 'Operating System']
dick = {}
for i,j in zip(list1, list2):
  dick[i] = j
print(dick)
print(list1[1])

def reversing(string):
  for i in range(len(string)-1,-1,-1):
    print(string[i], end = "")
reversing("bapi")
#reverisng using generators
def reversable(string):
  return "".join((string[x] for x in range(len(string)-1,-1,-1)))
print(reversable("bapi"))

def decorated(function):
  def inner(*args, **kwargs):
    print("i got decorated")
    function(*args, **kwargs)
  return inner
@decorated

def ordinary():
  print("i am ordinary")
ordinary()
ordinary= decorated(ordinary)
ordinary()

import math
h = map(int,input("enter H values: ").split(','))
q = [math.sqrt((2*50*i)/30) for i in h]
print(q)

class shape:
  def area(self):
    pass
class square(shape):
  def __init__(self, length):
    self.length = length
  def area(self):
    return self.length * self.length
sq = square(5)
sq.area()

# return a list of lists of length 3 
def three_Sum(num):
    if len(num)<3: return []
    num.sort()
    result=[]
    for i in range(len(num)-2):
        left=i+1
        right=len(num)-1
        if i!=0 and num[i]==num[i-1]:continue
        while left<right:
            if num[left]+num[right]==-num[i]:
                result.append([num[i],num[left],num[right]])
                left=left+1
                right=right-1
                while num[left]==num[left-1] and left<right:left=left+1
                while num[right]==num[right+1] and left<right: right=right-1
            elif num[left]+num[right]<-num[i]:
                left=left+1
            else:
                right=right-1
    return result
 
nums1=[-1,0,1,2,-1,-4]
nums2 = [-25,-10,-7,-3,2,4,8,10]
print(three_Sum(nums1))
print(three_Sum(nums2))

